<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Reqnroll.xunit.v3" Version="3.3.4" />
    <PackageReference Include="xunit.v3" Version="4.0.1" />
    <PackageReference Include="Shouldly" Version="4.3.0" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.12.0" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="2.5.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../VetPass.Testing/VetPass.Testing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Shouldly" />
    <Using Include="Reqnroll" />
    <Using Include="System.Net" />
    <Using Include="System.Net.Http.Json" />
    <Using Include="System.Text.Json" />
    <Using Include="VetPass.Testing" />
  </ItemGroup>

</Project>
