// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VetPass.API.Shared.Infrastructure.Persistence.EFC.Configuration;

#nullable disable

namespace VetPass.API.Shared.Infrastructure.Persistence.EFC.Migrations
{
    [DbContext(typeof(VetPassDbContext))]
    partial class VetPassDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("vetpass")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VetPass.API.IAM.Domain.Model.Aggregates.Clinic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("clinics", "vetpass");
                });

            modelBuilder.Entity("VetPass.API.IAM.Domain.Model.Aggregates.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid?>("ClinicId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinic_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("full_name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClinicId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("user_profiles", "vetpass");
                });

            modelBuilder.Entity("VetPass.API.MedicalRecords.Domain.Model.Aggregates.Visit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("diagnosis");

                    b.Property<string>("Findings")
                        .HasColumnType("text")
                        .HasColumnName("findings");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uuid")
                        .HasColumnName("pet_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("reason");

                    b.Property<string>("Treatment")
                        .HasColumnType("text")
                        .HasColumnName("treatment");

                    b.Property<Guid>("VeterinarianId")
                        .HasColumnType("uuid")
                        .HasColumnName("veterinarian_id");

                    b.Property<DateOnly>("VisitDate")
                        .HasColumnType("date")
                        .HasColumnName("visit_date");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id");

                    b.HasIndex("VeterinarianId");

                    b.HasIndex("PetId", "VisitDate");

                    b.ToTable("visits", "vetpass");
                });

            modelBuilder.Entity("VetPass.API.MedicalRecords.Domain.Model.Entities.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.HasKey("Id");

                    b.HasIndex("VisitId")
                        .IsUnique();

                    b.ToTable("prescriptions", "vetpass");
                });

            modelBuilder.Entity("VetPass.API.MedicalRecords.Domain.Model.ValueObjects.PrescriptionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("dosage");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("duration");

                    b.Property<string>("Medication")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("medication");

                    b.Property<Guid>("PrescriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("prescription_id");

                    b.HasKey("Id");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("prescription_items", "vetpass");
                });

            modelBuilder.Entity("VetPass.API.Patients.Domain.Model.Aggregates.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinic_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("full_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("FullName");

                    b.ToTable("clients", "vetpass");
                });

            modelBuilder.Entity("VetPass.API.Patients.Domain.Model.Aggregates.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Breed")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("breed");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sex");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("species");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("Name");

                    b.ToTable("pets", "vetpass");
                });

            modelBuilder.Entity("VetPass.API.Vaccination.Domain.Model.Aggregates.VaccinationCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("PetBirthDate")
                        .HasColumnType("date")
                        .HasColumnName("pet_birth_date");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uuid")
                        .HasColumnName("pet_id");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("species");

                    b.HasKey("Id");

                    b.HasIndex("PetId")
                        .IsUnique();

                    b.ToTable("vaccination_cards", "vetpass");
                });

            modelBuilder.Entity("VetPass.API.Vaccination.Domain.Model.Entities.Dose", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("ApplicationDate")
                        .HasColumnType("date")
                        .HasColumnName("application_date");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_id");

                    b.Property<DateOnly>("ExpectedDate")
                        .HasColumnType("date")
                        .HasColumnName("expected_date");

                    b.Property<int>("MinimumAgeInWeeks")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_age_weeks");

                    b.Property<int>("MinimumIntervalInWeeks")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_interval_weeks");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("VaccineId")
                        .HasColumnType("uuid")
                        .HasColumnName("vaccine_id");

                    b.Property<Guid?>("VeterinarianId")
                        .HasColumnType("uuid")
                        .HasColumnName("veterinarian_id");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("Status");

                    b.HasIndex("VaccineId");

                    b.HasIndex("VeterinarianId");

                    b.ToTable("doses", "vetpass");
                });

            modelBuilder.Entity("VetPass.API.Vaccination.Domain.Model.Entities.Vaccine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsCore")
                        .HasColumnType("boolean")
                        .HasColumnName("is_core");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("species");

                    b.HasKey("Id");

                    b.ToTable("vaccines", "vetpass");
                });

            modelBuilder.Entity("VetPass.API.Vaccination.Domain.Model.ValueObjects.ScheduleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("MinimumAgeInWeeks")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_age_weeks");

                    b.Property<int>("MinimumIntervalInWeeks")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_interval_weeks");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("species");

                    b.Property<Guid>("VaccineId")
                        .HasColumnType("uuid")
                        .HasColumnName("vaccine_id");

                    b.HasKey("Id");

                    b.HasIndex("VaccineId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("schedule_items", "vetpass");
                });

            modelBuilder.Entity("VetPass.API.IAM.Domain.Model.Aggregates.UserProfile", b =>
                {
                    b.HasOne("VetPass.API.Patients.Domain.Model.Aggregates.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VetPass.API.IAM.Domain.Model.Aggregates.Clinic", null)
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VetPass.API.MedicalRecords.Domain.Model.Aggregates.Visit", b =>
                {
                    b.HasOne("VetPass.API.Patients.Domain.Model.Aggregates.Pet", null)
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VetPass.API.IAM.Domain.Model.Aggregates.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("VeterinarianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VetPass.API.MedicalRecords.Domain.Model.Entities.Prescription", b =>
                {
                    b.HasOne("VetPass.API.MedicalRecords.Domain.Model.Aggregates.Visit", null)
                        .WithOne("Prescription")
                        .HasForeignKey("VetPass.API.MedicalRecords.Domain.Model.Entities.Prescription", "VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VetPass.API.MedicalRecords.Domain.Model.ValueObjects.PrescriptionItem", b =>
                {
                    b.HasOne("VetPass.API.MedicalRecords.Domain.Model.Entities.Prescription", null)
                        .WithMany("Items")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VetPass.API.Patients.Domain.Model.Aggregates.Client", b =>
                {
                    b.HasOne("VetPass.API.IAM.Domain.Model.Aggregates.Clinic", null)
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VetPass.API.Patients.Domain.Model.Aggregates.Pet", b =>
                {
                    b.HasOne("VetPass.API.Patients.Domain.Model.Aggregates.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VetPass.API.Vaccination.Domain.Model.Aggregates.VaccinationCard", b =>
                {
                    b.HasOne("VetPass.API.Patients.Domain.Model.Aggregates.Pet", null)
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VetPass.API.Vaccination.Domain.Model.Entities.Dose", b =>
                {
                    b.HasOne("VetPass.API.Vaccination.Domain.Model.Aggregates.VaccinationCard", null)
                        .WithMany("Doses")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VetPass.API.Vaccination.Domain.Model.Entities.Vaccine", null)
                        .WithMany()
                        .HasForeignKey("VaccineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VetPass.API.IAM.Domain.Model.Aggregates.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("VeterinarianId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("VetPass.API.Vaccination.Domain.Model.ValueObjects.BatchCode", "BatchCode", b1 =>
                        {
                            b1.Property<Guid>("DoseId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("batch_code");

                            b1.HasKey("DoseId");

                            b1.ToTable("doses", "vetpass");

                            b1.WithOwner()
                                .HasForeignKey("DoseId");
                        });

                    b.Navigation("BatchCode");
                });

            modelBuilder.Entity("VetPass.API.Vaccination.Domain.Model.ValueObjects.ScheduleItem", b =>
                {
                    b.HasOne("VetPass.API.Vaccination.Domain.Model.Entities.Vaccine", null)
                        .WithMany()
                        .HasForeignKey("VaccineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VetPass.API.MedicalRecords.Domain.Model.Aggregates.Visit", b =>
                {
                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("VetPass.API.MedicalRecords.Domain.Model.Entities.Prescription", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("VetPass.API.Vaccination.Domain.Model.Aggregates.VaccinationCard", b =>
                {
                    b.Navigation("Doses");
                });
#pragma warning restore 612, 618
        }
    }
}
